### PR TITLE
fix installation step for `lsp_dap`

### PR DESCRIPTION
**Pull request by askazakov**
since https://github.com/erlang-ls/erlang_ls/pull/1447 els_dap is in separate repo

### CODE REVIEW

**Comment by askazakov** [comment]
@the-mikedavis could you help me with issue that you have mentioned (about [nopr-flake-dap-fixes](https://github.com/the-mikedavis/erlang_ls/tree/nopr-flake-dap-fixes) branch) Is it actual?

**Comment by askazakov** [comment]
should I drop section about ErlangLS ? It is not necessary to have ErlangLS for this tutorial

**Comment by the-mikedavis** [comment]
> should I drop section about ErlangLS ? It is not necessary to have ErlangLS for this tutorial

Yeah let's drop that section, installing the language server shouldn't be necessary

**Comment by the-mikedavis** [comment]
I think I upstreamed all the fixes on that branch, so it should no longer be necessary to build erlang_ls from that branch or use a special helix build: https://github.com/erlang-ls/erlang_ls/pull/1347, https://github.com/erlang-ls/erlang_ls/pull/1345, https://github.com/erlang-ls/erlang_ls/pull/1346 / https://github.com/helix-editor/helix/pull/2959

**Review by the-mikedavis — APPROVED** [review]
Thank you!

**Pull request merged**
